from flask import Flask, render_template, jsonify, request, redirect, url_for
import os
import subprocess
import re
import yaml
from datetime import datetime, timezone

app = Flask(__name__)

CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.environ.get('ENV_FILE', os.path.join(CONFIG_DIR, ".env"))
KUBECONFIG_FILE = os.environ.get('KUBECONFIG_FILE', os.path.join(CONFIG_DIR, "kubeconfig"))
TERRAFORM_DIR = os.environ.get('TERRAFORM_DIR', os.path.dirname(os.path.abspath(__file__)))
TERRAFORM_VARS_FILE = os.path.join(TERRAFORM_DIR, "terraform.tfvars")

# ============ CONFIG FUNCTIONS ============

def load_env():
    env_vars = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    if "='''" in line:
                        # Multiline value
                        key = line.split("='''")[0].strip()
                        continue
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip().strip('"').strip("'")
    return env_vars

def save_env(data):
    with open(ENV_FILE, "w") as f:
        f.write("# RKE2 Autoscaler Dashboard Configuration\n")
        f.write("# Auto-generated by setup wizard\n\n")
        for key, value in data.items():
            if "\n" in str(value):
                f.write(f"{key}='''\n{value}\n'''\n")
            else:
                f.write(f'{key}="{value}"\n')
    return True

def is_configured():
    env = load_env()
    proxmox_ok = bool(env.get("PROXMOX_ENDPOINT"))
    kubeconfig_ok = os.path.exists(KUBECONFIG_FILE) and os.path.getsize(KUBECONFIG_FILE) > 0
    return proxmox_ok and kubeconfig_ok

def check_auth():
    """Check if request has valid password"""
    auth_header = request.headers.get('Authorization', '')
    if not auth_header.startswith('Bearer '):
        return False
    token = auth_header[7:]
    env = load_env()
    expected = env.get('DASHBOARD_TOKEN', '')
    return token == expected

def require_auth(f):
    """Decorator to require authentication for API routes"""
    from functools import wraps
    @wraps(f)
    def decorated(*args, **kwargs):
        if not check_auth():
            return jsonify({"error": "Unauthorized. Please login."}), 401
        return f(*args, **kwargs)
    return decorated

def get_var_from_tfvars(var_name):
    try:
        with open(TERRAFORM_VARS_FILE, "r") as f:
            content = f.read()
            match = re.search(rf'{var_name}\s*=\s*(.+)', content)
            if match:
                value = match.group(1).strip()
                if value.isdigit():
                    return int(value)
                return value
    except Exception:
        pass
    return None

def set_var_in_tfvars(var_name, value):
    try:
        with open(TERRAFORM_VARS_FILE, "r") as f:
            content = f.read()

        if re.search(rf'{var_name}\s*=', content):
            new_content = re.sub(rf'{var_name}\s*=\s*.+', f'{var_name} = {value}', content)
        else:
            new_content = content + f"\n{var_name} = {value}"

        with open(TERRAFORM_VARS_FILE, "w") as f:
            f.write(new_content)
        return True
    except Exception:
        return False

def get_current_worker_count():
    return get_var_from_tfvars("worker_count") or 0

def get_worker_cpu():
    return get_var_from_tfvars("worker_cpu") or 2

def get_worker_memory():
    return get_var_from_tfvars("worker_memory") or 4096

# ============ TERRAFORM FUNCTIONS ============

def run_terraform(action="plan"):
    try:
        os.chdir(TERRAFORM_DIR)
        env = load_env()

        # Set Terraform environment variables from .env
        tf_env = os.environ.copy()
        if env.get("PROXMOX_ENDPOINT"):
            tf_env["TF_VAR_proxmox_endpoint"] = env["PROXMOX_ENDPOINT"]
        if env.get("PROXMOX_USERNAME"):
            tf_env["TF_VAR_proxmox_username"] = env["PROXMOX_USERNAME"]
        if env.get("PROXMOX_PASSWORD"):
            tf_env["TF_VAR_proxmox_password"] = env["PROXMOX_PASSWORD"]
        if env.get("VM_PASSWORD"):
            tf_env["TF_VAR_vm_password"] = env["VM_PASSWORD"]

        # Auto init if needed (idempotent, safe for existing state)
        init_result = subprocess.run(
            ["terraform", "init", "-no-color"],
            capture_output=True, text=True, timeout=120, env=tf_env
        )
        if init_result.returncode != 0:
            return {"success": False, "output": "Init failed: " + init_result.stdout + init_result.stderr}

        if action == "plan":
            result = subprocess.run(["terraform", "plan", "-no-color"], capture_output=True, text=True, timeout=60, env=tf_env)
        else:
            result = subprocess.run(["terraform", "apply", "-auto-approve", "-no-color"], capture_output=True, text=True, timeout=300, env=tf_env)
        return {"success": result.returncode == 0, "output": result.stdout + result.stderr}
    except subprocess.TimeoutExpired:
        return {"success": False, "output": "Timeout: Terraform took too long"}
    except Exception as e:
        return {"success": False, "output": str(e)}

def get_terraform_status():
    try:
        result = subprocess.run(["terraform", "show", "-json"], capture_output=True, text=True, cwd=TERRAFORM_DIR, timeout=30)
        if result.returncode == 0:
            import json
            data = json.loads(result.stdout)
            resources = data.get("values", {}).get("root_module", {}).get("resources", [])
            workers = [r for r in resources if r.get("type") == "proxmox_virtual_environment_vm"]
            return {"success": True, "workers": len(workers), "resources": workers}
        return {"success": False, "workers": 0, "resources": []}
    except Exception:
        return {"success": False, "workers": 0, "resources": []}

# ============ K8S FUNCTIONS ============

def get_k8s_nodes():
    try:
        if not os.path.exists(KUBECONFIG_FILE):
            return {"success": False, "error": "kubeconfig not found", "nodes": []}

        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "get", "nodes", "-o", "yaml"],
            capture_output=True, text=True, timeout=30
        )

        if result.returncode == 0:
            data = yaml.safe_load(result.stdout)
            items = data.get("items", [])
            nodes = []

            for item in items:
                status = item.get("status", {})
                conditions = status.get("conditions", [])
                ready = next((c for c in conditions if c.get("type") == "Ready"), {})
                roles = []
                labels = item.get("metadata", {}).get("labels", {})

                if labels.get("node-role.kubernetes.io/master") == "true":
                    roles.append("master")
                if labels.get("node-role.kubernetes.io/control-plane") == "true":
                    roles.append("control-plane")
                if labels.get("node-role.kubernetes.io/worker") == "true":
                    roles.append("worker")

                # Calculate uptime from node creation timestamp
                creation_ts = item.get("metadata", {}).get("creationTimestamp", None)
                uptime = "-"
                if creation_ts:
                    try:
                        ts = datetime.fromisoformat(creation_ts.replace("Z", "+00:00"))
                        now = datetime.now(timezone.utc)
                        delta = now - ts
                        days = delta.days
                        hours, remainder = divmod(delta.seconds, 3600)
                        minutes = remainder // 60
                        if days > 0:
                            uptime = f"{days}d {hours}h"
                        elif hours > 0:
                            uptime = f"{hours}h {minutes}m"
                        else:
                            uptime = f"{minutes}m"
                    except:
                        pass

                nodes.append({
                    "name": item.get("metadata", {}).get("name"),
                    "roles": roles,
                    "status": ready.get("status", "Unknown"),
                    "version": status.get("nodeInfo", {}).get("kubeletVersion", "-"),
                    "age": item.get("metadata", {}).get("creationTimestamp", "-"),
                    "cpu": status.get("allocatable", {}).get("cpu", "-"),
                    "memory": status.get("allocatable", {}).get("memory", "-"),
                    "uptime": uptime
                })
            return {"success": True, "nodes": nodes}
        return {"success": False, "error": result.stderr, "nodes": []}
    except Exception as e:
        return {"success": False, "error": str(e), "nodes": []}

def get_worker_names_to_remove(old_count, new_count):
    if old_count <= new_count:
        return []
    workers = []
    for i in range(new_count + 1, old_count + 1):
        workers.append(f"rke2-worker-{i:02d}")
    return workers

def get_all_worker_nodes():
    if not os.path.exists(KUBECONFIG_FILE):
        return []
    try:
        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "get", "nodes", "-o", "jsonpath={.items[*].metadata.name}"],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            all_nodes = result.stdout.strip().split()
            return [n for n in all_nodes if n.startswith("rke2-worker-")]
    except Exception:
        pass
    return []

def k8s_scale_down_workers(worker_names):
    if not os.path.exists(KUBECONFIG_FILE):
        return {"success": False, "error": "kubeconfig not found", "results": []}

    results = []
    for worker_name in worker_names:
        action_result = {"worker": worker_name, "steps": []}

        for action, cmd in [
            ("cordon", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "cordon", worker_name]),
            ("drain", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "drain", worker_name, "--ignore-daemonsets", "--delete-emptydir-data", "--force", "--grace-period=30", "--timeout=120s"]),
            ("delete_node", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "delete", "node", worker_name, "--grace-period=0", "--force"])
        ]:
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
                action_result["steps"].append({"action": action, "success": result.returncode == 0, "output": result.stdout + result.stderr})
            except Exception as e:
                action_result["steps"].append({"action": action, "success": False, "output": str(e)})

        results.append(action_result)

    all_success = all(all(step["success"] for step in r["steps"]) for r in results)
    return {"success": all_success, "results": results}

# ============ SETUP ROUTES ============

@app.route("/")
def index():
    if not is_configured():
        return redirect(url_for("setup"))
    return render_template("index.html")

@app.route("/setup")
def setup():
    if is_configured():
        return redirect(url_for("index"))

    env = load_env()
    return render_template("setup.html",
        proxmox_endpoint=env.get("PROXMOX_ENDPOINT", "https://10.12.0.1:8006/api2/json/"),
        proxmox_username=env.get("PROXMOX_USERNAME", "root@pam"),
        proxmox_password=env.get("PROXMOX_PASSWORD", ""),
        kubeconfig_content=""
    )

@app.route("/api/config", methods=["GET"])
@require_auth
def get_config():
    env = load_env()
    kubeconfig_exists = os.path.exists(KUBECONFIG_FILE) and os.path.getsize(KUBECONFIG_FILE) > 0
    return jsonify({
        "configured": is_configured(),
        "has_proxmox": bool(env.get("PROXMOX_ENDPOINT")),
        "has_kubeconfig": kubeconfig_exists
    })

@app.route("/api/login", methods=["POST"])
def login():
    """Login to get auth token"""
    data = request.get_json()
    password = data.get("password", "")

    env = load_env()
    stored_password = env.get("DASHBOARD_PASSWORD", "")

    if stored_password and password == stored_password:
        token = env.get("DASHBOARD_TOKEN", "")
        return jsonify({"success": True, "token": token})

    return jsonify({"success": False, "error": "Invalid password"}), 401

@app.route("/api/proxmox/resources", methods=["GET", "POST"])
def proxmox_resources():
    """Get available nodes and templates from Proxmox"""
    env = load_env()

    # Support POST with inline credentials (for setup wizard)
    if request.method == "POST":
        data = request.get_json() or {}
        endpoint = data.get("proxmox_endpoint", "")
        username = data.get("proxmox_username", "")
        password = data.get("proxmox_password", "")
    else:
        endpoint = env.get("PROXMOX_ENDPOINT", "")
        username = env.get("PROXMOX_USERNAME", "")
        password = env.get("PROXMOX_PASSWORD", "")

    if not all([endpoint, username, password]):
        return jsonify({"error": "Proxmox not configured"}), 400

    try:
        from proxmoxer import ProxmoxAPI
        import urllib3
        urllib3.disable_warnings()

        # Extract host and port from endpoint
        host = endpoint.replace("https://", "").split(":")[0]
        port = int(endpoint.split(":")[-1].replace("/api2/json", "").strip())

        proxmox = ProxmoxAPI(host, port=port, user=username, password=password, verify_ssl=False)

        # Get nodes
        all_nodes = []
        try:
            for node in proxmox.nodes.get():
                all_nodes.append({
                    "node": node.get("node"),
                    "status": node.get("status", "unknown")
                })
        except Exception as e:
            return jsonify({"error": f"Failed to get nodes: {str(e)}"}), 500

        # Get templates from each node
        templates = {}
        for node_info in all_nodes:
            node_name = node_info["node"]
            try:
                qemu = proxmox.nodes(node_name).qemu.get()
                node_templates = []
                for v in qemu:
                    if v.get("template") == 1:
                        node_templates.append({
                            "vmid": v.get("vmid"),
                            "name": v.get("name")
                        })
                if node_templates:
                    templates[node_name] = node_templates
            except:
                pass

        return jsonify({
            "success": True,
            "nodes": all_nodes,
            "templates": templates
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/config", methods=["POST"])
def save_config():
    data = request.get_json()
    required = ["proxmox_endpoint", "proxmox_username", "proxmox_password", "kubeconfig_content", "vm_password"]
    for field in required:
        if not data.get(field):
            return jsonify({"error": f"{field} is required"}), 400

    # Write kubeconfig to file
    with open(KUBECONFIG_FILE, "w") as f:
        f.write(data["kubeconfig_content"])

    # Generate a simple token if not exists
    import secrets
    import json
    token = secrets.token_hex(32)

    # Handle template_per_node
    template_per_node = data.get("template_per_node", {})
    if isinstance(template_per_node, dict):
        template_per_node_str = json.dumps(template_per_node)
    else:
        template_per_node_str = str(template_per_node)

    # Save env
    env_data = {
        "PROXMOX_ENDPOINT": data["proxmox_endpoint"],
        "PROXMOX_USERNAME": data["proxmox_username"],
        "PROXMOX_PASSWORD": data["proxmox_password"],
        "VM_PASSWORD": data["vm_password"],
        "KUBECONFIG_PATH": KUBECONFIG_FILE,
        "DASHBOARD_TOKEN": token,
        "DASHBOARD_PASSWORD": data.get("dashboard_password", secrets.token_hex(8)),
        "TEMPLATE_PER_NODE": template_per_node_str
    }
    save_env(env_data)

    return jsonify({"success": True, "message": "Configuration saved", "token": token})

# ============ API ROUTES ============

@app.route("/api/status")
@require_auth
def status():
    tf_status = get_terraform_status()
    k8s_status = get_k8s_nodes()
    return jsonify({
        "worker_count": get_current_worker_count(),
        "worker_cpu": get_worker_cpu(),
        "worker_memory": get_worker_memory(),
        "deployed_workers": tf_status.get("workers", 0),
        "tf_success": tf_status.get("success", False),
        "k8s_enabled": os.path.exists(KUBECONFIG_FILE),
        "k8s_nodes": k8s_status.get("nodes", []),
        "k8s_error": k8s_status.get("error", None)
    })

@app.route("/api/worker-count", methods=["GET"])
@require_auth
def get_worker():
    return jsonify({"worker_count": get_current_worker_count()})

@app.route("/api/worker-count", methods=["POST"])
@require_auth
def set_worker():
    data = request.get_json()
    new_count = data.get("worker_count", 0)
    if not isinstance(new_count, int) or new_count < 0:
        return jsonify({"error": "Invalid worker_count"}), 400
    if new_count > 10:
        return jsonify({"error": "Maximum 10 workers allowed"}), 400
    if set_var_in_tfvars("worker_count", new_count):
        return jsonify({"success": True, "worker_count": new_count})
    return jsonify({"error": "Failed to update terraform.tfvars"}), 500

@app.route("/api/worker-cpu", methods=["GET"])
@require_auth
def get_cpu():
    return jsonify({"worker_cpu": get_worker_cpu()})

@app.route("/api/worker-cpu", methods=["POST"])
@require_auth
def set_cpu():
    data = request.get_json()
    new_cpu = data.get("worker_cpu", 2)
    if not isinstance(new_cpu, int) or new_cpu < 1 or new_cpu > 32:
        return jsonify({"error": "Invalid worker_cpu (1-32)"}), 400
    if set_var_in_tfvars("worker_cpu", new_cpu):
        return jsonify({"success": True, "worker_cpu": new_cpu})
    return jsonify({"error": "Failed to update terraform.tfvars"}), 500

@app.route("/api/worker-memory", methods=["GET"])
@require_auth
def get_memory():
    return jsonify({"worker_memory": get_worker_memory()})

@app.route("/api/worker-memory", methods=["POST"])
@require_auth
def set_memory():
    data = request.get_json()
    new_memory = data.get("worker_memory", 4096)
    if not isinstance(new_memory, int) or new_memory < 512 or new_memory > 65536:
        return jsonify({"error": "Invalid worker_memory (512-65536 MB)"}), 400
    if set_var_in_tfvars("worker_memory", new_memory):
        return jsonify({"success": True, "worker_memory": new_memory})
    return jsonify({"error": "Failed to update terraform.tfvars"}), 500

@app.route("/api/terraform/plan", methods=["POST"])
@require_auth
def terraform_plan():
    return jsonify(run_terraform("plan"))

@app.route("/api/terraform/apply", methods=["POST"])
@require_auth
def terraform_apply():
    return jsonify(run_terraform("apply"))

@app.route("/api/scale-down", methods=["POST"])
@require_auth
def scale_down():
    """Handle scale down - cordon & drain, but DON'T delete K8s node yet"""
    data = request.get_json()
    new_worker_count = data.get("worker_count")

    if new_worker_count is None:
        return jsonify({"error": "worker_count required"}), 400

    current_count = get_current_worker_count()

    if new_worker_count >= current_count:
        set_var_in_tfvars("worker_count", new_worker_count)
        tf_result = run_terraform("apply")
        return jsonify({"action": "scale_up_or_same", "worker_count": new_worker_count, "terraform": tf_result})

    workers_to_remove = get_worker_names_to_remove(current_count, new_worker_count)

    if new_worker_count == 0:
        workers_to_remove = get_all_worker_nodes()

    # Update terraform.tfvars first
    set_var_in_tfvars("worker_count", new_worker_count)

    # Only cordon & drain - DON'T delete K8s node yet
    k8s_result = k8s_cordon_drain_workers(workers_to_remove)

    # Run terraform apply (this will delete the VMs)
    tf_result = run_terraform("apply")

    return jsonify({
        "action": "scale_down",
        "worker_count": new_worker_count,
        "workers_removed": workers_to_remove,
        "k8s_drain": k8s_result,
        "terraform": tf_result,
        "note": "K8s nodes still exist. Use 'Delete Node' button to remove them."
    })


def k8s_cordon_drain_workers(worker_names):
    """Cordon and drain K8s nodes (without deleting)"""
    if not os.path.exists(KUBECONFIG_FILE):
        return {"success": False, "error": "kubeconfig not found", "results": []}

    results = []
    for worker_name in worker_names:
        action_result = {"worker": worker_name, "steps": []}

        # Step 1: Cordon
        try:
            result = subprocess.run(
                ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "cordon", worker_name],
                capture_output=True, text=True, timeout=30
            )
            action_result["steps"].append({
                "action": "cordon",
                "success": result.returncode == 0,
                "output": result.stdout + result.stderr
            })
        except Exception as e:
            action_result["steps"].append({"action": "cordon", "success": False, "output": str(e)})

        # Step 2: Drain
        try:
            result = subprocess.run(
                ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "drain", worker_name,
                 "--ignore-daemonsets", "--delete-emptydir-data", "--force",
                 "--grace-period=30", "--timeout=120s"],
                capture_output=True, text=True, timeout=180
            )
            action_result["steps"].append({
                "action": "drain",
                "success": result.returncode == 0,
                "output": result.stdout + result.stderr
            })
        except Exception as e:
            action_result["steps"].append({"action": "drain", "success": False, "output": str(e)})

        results.append(action_result)

    all_success = all(all(step["success"] for step in r["steps"]) for r in results)
    return {"success": all_success, "results": results}

@app.route("/api/k8s/nodes", methods=["GET"])
@require_auth
def k8s_nodes():
    return jsonify(get_k8s_nodes())

@app.route("/api/k8s/cordon", methods=["POST"])
@require_auth
def k8s_cordon():
    """Cordon a node (mark as unschedulable)"""
    data = request.get_json()
    node_name = data.get("node_name", "").strip()

    if not node_name:
        return jsonify({"error": "node_name is required"}), 400

    try:
        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "cordon", node_name],
            capture_output=True, text=True, timeout=30
        )
        return jsonify({
            "success": result.returncode == 0,
            "output": result.stdout + result.stderr
        })
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route("/api/k8s/drain", methods=["POST"])
@require_auth
def k8s_drain():
    """Drain a node (evict all pods)"""
    data = request.get_json()
    node_name = data.get("node_name", "").strip()

    if not node_name:
        return jsonify({"error": "node_name is required"}), 400

    try:
        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "drain", node_name,
             "--ignore-daemonsets", "--delete-emptydir-data", "--force",
             "--grace-period=30", "--timeout=120s"],
            capture_output=True, text=True, timeout=180
        )
        return jsonify({
            "success": result.returncode == 0,
            "output": result.stdout + result.stderr
        })
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route("/api/k8s/delete-node", methods=["POST"])
@require_auth
def k8s_delete_node():
    """Delete a node from K8s cluster"""
    data = request.get_json()
    node_name = data.get("node_name", "").strip()

    if not node_name:
        return jsonify({"error": "node_name is required"}), 400

    try:
        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "delete", "node", node_name,
             "--grace-period=0", "--force"],
            capture_output=True, text=True, timeout=30
        )
        return jsonify({
            "success": result.returncode == 0,
            "output": result.stdout + result.stderr
        })
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route("/api/k8s/pods", methods=["GET"])
@require_auth
def k8s_pods():
    """Get pods running on a specific node"""
    node_name = request.args.get("node_name", "").strip()

    if not node_name:
        return jsonify({"error": "node_name is required"}), 400

    try:
        # Get pods on the node from all namespaces
        result = subprocess.run(
            ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "get", "pods", "--all-namespaces", "-o", "wide",
             "--field-selector", f"spec.nodeName={node_name}"],
            capture_output=True, text=True, timeout=30
        )

        if result.returncode == 0:
            lines = result.stdout.strip().split("\n")
            if len(lines) <= 1:
                return jsonify({"success": True, "pods": [], "count": 0, "node": node_name, "output": "No pods found on node"})

            # Skip header line, parse data lines
            pods = []
            for line in lines[1:]:
                # Split by whitespace but only take first 6 fields (namespace, name, ready, status, restarts, age)
                # Then ignore the rest (IP, node, etc.)
                parts = line.split()
                if len(parts) >= 6:
                    pod = {
                        "namespace": parts[0],
                        "name": parts[1],
                        "ready": parts[2],
                        "status": parts[3],
                        "restarts": parts[4],
                        "age": parts[5],
                    }
                    pods.append(pod)

            return jsonify({
                "success": True,
                "pods": pods,
                "count": len(pods),
                "node": node_name
            })

        return jsonify({"success": False, "error": result.stderr, "pods": []})

    except Exception as e:
        return jsonify({"success": False, "error": str(e), "pods": []})

@app.route("/api/k8s/drain-delete", methods=["POST"])
@require_auth
def k8s_drain_delete():
    """Cordon, drain, and delete a node"""
    data = request.get_json()
    node_name = data.get("node_name", "").strip()

    if not node_name:
        return jsonify({"error": "node_name is required"}), 400

    results = {"node": node_name, "steps": []}

    for action, cmd in [
        ("cordon", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "cordon", node_name]),
        ("drain", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "drain", node_name, "--ignore-daemonsets", "--delete-emptydir-data", "--force", "--grace-period=30", "--timeout=120s"]),
        ("delete_node", ["kubectl", "--kubeconfig", KUBECONFIG_FILE, "delete", "node", node_name, "--grace-period=0", "--force"])
    ]:
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            results["steps"].append({"action": action, "success": result.returncode == 0, "output": result.stdout + result.stderr})
        except Exception as e:
            results["steps"].append({"action": action, "success": False, "output": str(e)})

    all_success = all(step["success"] for step in results["steps"])
    return jsonify({"success": all_success, "results": results})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)